name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-unit-tests:
    name: Build & unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install platform + build-tools
        run: |
          for i in 1 2 3; do
            sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.1" && break || sleep 15
          done
          yes | sdkmanager --licenses

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble Debug
        run: ./gradlew --stacktrace --no-daemon clean assembleDebug

      - name: Run unit tests
        run: ./gradlew --stacktrace --no-daemon testDebugUnitTest

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

  instrumented-tests:
    name: Instrumented tests (emulator)
    runs-on: ubuntu-latest
    needs: build-and-unit-tests
    timeout-minutes: 50

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages (emulator + system image)
        run: |
          for i in 1 2 3; do
            sdkmanager "platform-tools" \
                       "platforms;android-35" "build-tools;35.0.1" \
                       "emulator" \
                       "platforms;android-34" \
                       "system-images;android-34;google_apis;x86_64" \
            && break || sleep 15
          done
          yes | sdkmanager --licenses

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # IMPORTANT: task correcte per a l’APK de tests
      - name: Assemble app & androidTest
        run: ./gradlew --stacktrace --no-daemon :app:assembleDebug :app:assembleDebugAndroidTest
      - name: Run connected tests on API 33
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_6
          force-avd-creation: true
          emulator-boot-timeout: 1800
          disable-animations: true
          emulator-options: >-
            -no-window
            -gpu swiftshader_indirect
            -no-snapshot-load
            -no-snapshot-save
            -noaudio
            -no-boot-anim
            -camera-back none
            -camera-front none
          script: |
            adb devices
            # Espera que el dispositiu respongui
            adb wait-for-device
            # Espera que Android declari que ha completat l'arrencada
            adb shell 'while [[ "$(getprop sys.boot_completed)" != "1" ]]; do sleep 2; done'
            adb shell 'while [[ -z "$(getprop dev.bootcomplete)" ]]; do sleep 1; done'
            # Assegura que el Package Manager està disponible
            adb shell 'until pm list packages >/dev/null 2>&1; do sleep 2; done'
            # Desbloqueja pantalla (per si queda a l’escriptori de bloqueig)
            adb shell input keyevent 82 || true
            # Executa els tests instrumentats
            ./gradlew --stacktrace --no-daemon connectedDebugAndroidTest


      - name: Upload AndroidTest reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connected-android-test-report
          path: app/build/reports/androidTests/connected/**
