name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Assemble Debug (no tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Install platform + build-tools
        run: |
          for i in 1 2 3; do
            sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.1" && break || sleep 15
          done
          yes | sdkmanager --licenses

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - uses: gradle/actions/setup-gradle@v3

      - name: Assemble (skip tests)
        run: ./gradlew --stacktrace --no-daemon -x test :app:assembleDebug

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
